title: "webcam_to_vrm"
description: "A Playground to controle a vroid avatar with user pose estimation."
baseurl: "/webcam_to_vrm"
url: "https://europanite.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
highlighter: rouge